set UID=christian.hase
set UIDNUMBER=10805
set GIDNUMBER=10066
set GROUPS=e1fs4 schueler
set FULLNAME=Christian Hase
set FIRSTNAME=Christian
set LASTNAME=Hase
set DISPLAYNAME=Christian Hase
set MAIL=christian.hase@its-stuttgart.de
set LOGINSHELL=/bin/false
set ROLE=student
set OBJECTTYPE=
set OBJECTSUBTYPE=
set PYKOTALIMITBY=balance
set PYKOTABALANCE=10.0
set ROOM=0.210
set DOMAINNAME=its-stuttgart.de
set LDAP_BASE=dc=its-stuttgart,dc=de
set LDAP_HOST=ldap.its-stuttgart.de
set LDAP_PORT=389
set SMTP_HOST=mail.its-stuttgart.de
set SMTP_DOMAIN=its-stuttgart.de
set IMAP_HOST=mail.its-stuttgart.de
