# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1238069561);
user_pref("app.update.lastUpdateTime.background-update-timer", 1238069561);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1238069561);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1238069561);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1266226716);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1301508189);
user_pref("app.update.never.3.6", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.manager.alertOnEXEOpen", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.history_expire_days_min", 7);
user_pref("browser.migration.version", 5);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "http://homepage");
user_pref("browser.startup.homepage_override.buildID", "20110303194838");
user_pref("browser.startup.homepage_override.mstone", "rv:2.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.taskbar.lastgroupid", "Mozilla.Firefox.4.0");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.checkCompatibility", false);
user_pref("extensions.databaseSchema", 3);
user_pref("extensions.enabledAddons", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:4.0");
user_pref("extensions.enabledItems", "{CAFEEFAC-0016-0000-0018-ABCDEFFEDCBA}:6.0.18,jqs@sun.com:1.0,{20a82645-c095-46ed-80e3-08825760534b}:1.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1300097035000}}},{\"name\":\"app-profile\",\"addons\":{\"{20a82645-c095-46ed-80e3-08825760534b}\":{\"descriptor\":\"H:\\\\Profile\\\\Firefox\\\\extensions\\\\{20a82645-c095-46ed-80e3-08825760534b}\",\"mtime\":1301508223000}}}]");
user_pref("extensions.lastAppVersion", "4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("general.autoScroll", false);
user_pref("general.useragent.extra.microsoftdotnet", "(.NET CLR 3.5.30729)");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("microsoft.CLR.auto_install", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.type", 4);
user_pref("places.history.expiration.transient_current_max_pages", 122449);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.warn_entering_weak", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.migrated", true);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("startup.homepage_override_url", "");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1229886398);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.checkCompatibility", false);
user_pref("startup.homepage_override_url", "");
user_pref("app.update.enabled", false);
user_pref("browser.search.update", false);
user_pref("extensions.update.enabled", false);
